name: docker ci

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: build docker image
      run: |
        docker build . --tag l33tname/govc-alpine:${{ github.sha }}
        docker tag l33tname/govc-alpine:${{ github.sha }} l33tname/govc-alpine:unstable
    - name: tag latest and version on release
      if: startsWith(github.event.ref, 'refs/tags')
      run: |
        docker tag l33tname/govc-alpine:${{ github.sha }} l33tname/govc-alpine:$(git describe --tags)
        docker tag l33tname/govc-alpine:${{ github.sha }} l33tname/govc-alpine:latest   

    - uses: docker/login-action@v2
      with:
        username: 'l33tname'
        password: ${{ secrets.DOCKERHUB }}

    - name: publish docker image
      run: |
        docker push l33tname/govc-alpine
      env:
        DOCKERHUB: ${{ secrets.DOCKERHUB }}

    - name: Create Release
      if: startsWith(github.event.ref, 'refs/tags')
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Release ${{ github.ref }} generated by the CI.
          ```
          docker pull l33tname/govc-alpine:${{ github.ref }}
          ```
        draft: false
        prerelease: false
